version = "3.7.17"
runner.dialect = scala213
maxColumn = 320
align.preset = none
spaces.inImportCurlyBraces = false
optIn.configStyleArguments = false
newlines.source = keep
indent.callSite = 2
indent.defnSite = 2
indent.caseSite = 2
indent.extendSite = 0
danglingParentheses.callSite = true
danglingParentheses.defnSite = true
docstrings.style = Asterisk