name: Discussion Avatar CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    permissions:
      # required by actions/checkout
      contents: read
      # required by guardian/actions-riff-raff
      pull-requests: write
      id-token: write
    
    steps:
      - uses: actions/checkout@v4
      - uses: guardian/setup-scala@v1

      # TODO: Get scalafmt working
      # - run: sbt scalafmtCheck
      - run: sbt clean compile
        working-directory: api
      - run: sbt test
        working-directory: api
      - run: sbt packageZipTarball
        working-directory: api

      - name: Upload to RiffRaff
        uses: guardian/actions-riff-raff@v4
        with:
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: Discussion::avatar-api
          buildNumberOffset: 3000
          configPath: riff-raff.yaml
          contentDirectories: |
            avatar-api:
              - api/target/universal/avatar-api.tgz
            cfn:
              - cloudformation.yaml